const ExchangeRatesTypes = {
  FETCH_EXCHANGE_RATES_PENDING: 'FETCH_EXCHANGE_RATES_PENDING',
  FETCH_EXCHANGE_RATES_SUCCESS: 'FETCH_EXCHANGE_RATES_SUCCESS',
  FETCH_EXCHANGE_RATES_ERROR: 'FETCH_EXCHANGE_RATES_ERROR'
};

export default ExchangeRatesTypes;